export const userActionTypes = {
  SIGN_IN: 'USER_SIGN_IN',
  SIGN_UP: 'USER_SIGN_UP',
  SIGN_OUT: 'USER_SIGN_OUT',
  ERROR: 'USER_ERROR',
  LOADING: 'USER_LOADING',
  CLEAR_ERROR: 'USER_CLEAR_ERROR',
};
